name: Build Telegram Bot API

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        repository: tdlib/telegram-bot-api
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y make git zlib1g-dev libssl-dev gperf cmake g++

    - name: Build
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        cmake --build . --target telegram-bot-api

    - name: Package
      run: |
        cd build
        tar -czf telegram-bot-api.tar.gz telegram-bot-api

    - name: Generate release date
      id: date
      run: echo "date=$(date +'%Y%m')" >> $GITHUB_OUTPUT

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: build/telegram-bot-api.tar.gz
        tag_name: build-${{ steps.date.outputs.date }}
        name: Monthly Build ${{ steps.date.outputs.date }}
        body: |
          Monthly automated build of telegram-bot-api
          Build date: ${{ steps.date.outputs.date }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
