name: Build

on:
  schedule:
    - cron: '0 3 1 * *'
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
      actions: write
    strategy:
      matrix:
        compiler: [gcc, clang]
        include:
          - compiler: gcc
            cc: gcc
            cxx: g++
          - compiler: clang
            cc: clang
            cxx: clang++
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: tdlib/telegram-bot-api
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y make git zlib1g-dev libssl-dev gperf cmake g++ clang

      - name: Configure build
        env:
          CC: ${{ matrix.cc }}
          CXX: ${{ matrix.cxx }}
        run: |
          rm -rf build
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..

      - name: Build
        working-directory: build
        run: cmake --build .

      - name: Create Release Asset
        run: |
          cd build
          tar czf telegram-bot-api-${{ matrix.compiler }}.tar.gz telegram-bot-api

      - name: Generate release date
        id: date
        run: echo "date=$(date +'%F')" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.date.outputs.date }}
          tag_name: ${{ steps.date.outputs.date }}
          files: build/telegram-bot-api-${{ matrix.compiler }}.tar.gz
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/telegram-bot-api-${{ matrix.compiler }}.tar.gz
          asset_name: telegram-bot-api-${{ matrix.compiler }}.tar.gz
          asset_content_type: application/gzip
