name: Build

on:
  schedule:
    - cron: '0 3 1 * *'
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    strategy:
      matrix:
        compiler: [gcc, clang]
        include:
          - compiler: gcc
            cc: gcc
            cxx: g++
          - compiler: clang
            cc: clang
            cxx: clang++
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: tdlib/telegram-bot-api
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y make git zlib1g-dev libssl-dev gperf cmake g++ clang

      - name: Configure build
        env:
          CC: ${{ matrix.cc }}
          CXX: ${{ matrix.cxx }}
        run: |
          rm -rf build
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..

      - name: Build Telegram Bot API
        working-directory: build
        run: cmake --build .

      - name: Create Release Asset
        working-directory: build
        run: tar -czvf telegram-bot-api-${{ matrix.compiler }}.tar.gz telegram-bot-api

      - name: Generate release date
        id: date
        run: echo "date=$(date +'%F')" >> $GITHUB_OUTPUT

      - name: Generate release version
        id: version
        run: echo "version=Telegram $(./build/telegram-bot-api --version 2>&1)" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ steps.date.outputs.date }}
          tag_name: ${{ steps.date.outputs.date }}
          body: ${{ steps.version.outputs.version }}
          files: build/telegram-bot-api-${{ matrix.compiler }}.tar.gz
          generate_release_notes: true
